export type MooBuiltinMetadata = {
  minArgs: number;
  maxArgs: number;
  parameterTypes: readonly string[];
};

export const MOO_BUILTIN_METADATA = {
  abs: { minArgs: 1, maxArgs: 1, parameterTypes: ['numeric'] },
  acos: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  acosh: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  add_property: { minArgs: 4, maxArgs: 4, parameterTypes: ['any', 'str', 'any', 'list'] },
  add_verb: { minArgs: 3, maxArgs: 3, parameterTypes: ['any', 'list', 'list'] },
  all_members: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'list'] },
  ancestors: { minArgs: 1, maxArgs: 2, parameterTypes: ['any', 'any'] },
  anon: { minArgs: 0, maxArgs: 2, parameterTypes: ['list', 'any'] },
  argon2: { minArgs: 2, maxArgs: 5, parameterTypes: ['str', 'str', 'int', 'int', 'int'] },
  argon2_verify: { minArgs: 2, maxArgs: 2, parameterTypes: ['str', 'str'] },
  asin: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  asinh: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  atan: { minArgs: 1, maxArgs: 2, parameterTypes: ['float', 'float'] },
  atan2: { minArgs: 2, maxArgs: 2, parameterTypes: ['float', 'float'] },
  atanh: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  background_test: { minArgs: 0, maxArgs: 2, parameterTypes: ['str', 'int'] },
  binary_hash: { minArgs: 1, maxArgs: 3, parameterTypes: ['str', 'str', 'any'] },
  binary_hmac: { minArgs: 2, maxArgs: 4, parameterTypes: ['str', 'str', 'str', 'any'] },
  boot_player: { minArgs: 1, maxArgs: 1, parameterTypes: ['obj'] },
  buffered_output_length: { minArgs: 0, maxArgs: 1, parameterTypes: ['obj'] },
  call_function: { minArgs: 1, maxArgs: -1, parameterTypes: ['str'] },
  caller_perms: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  callers: { minArgs: 0, maxArgs: 1, parameterTypes: ['any'] },
  cbrt: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  ceil: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  children: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  chparent: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'obj'] },
  chparents: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'list'] },
  chr: { minArgs: 0, maxArgs: -1, parameterTypes: [] },
  clear_property: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'str'] },
  connected_players: { minArgs: 0, maxArgs: 1, parameterTypes: ['any'] },
  connected_seconds: { minArgs: 1, maxArgs: 1, parameterTypes: ['obj'] },
  connection_info: { minArgs: 1, maxArgs: 1, parameterTypes: ['obj'] },
  connection_name: { minArgs: 1, maxArgs: 2, parameterTypes: ['obj', 'int'] },
  connection_name_lookup: { minArgs: 1, maxArgs: 2, parameterTypes: ['obj', 'any'] },
  connection_options: { minArgs: 1, maxArgs: 2, parameterTypes: ['obj', 'str'] },
  cos: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  cosh: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  create: { minArgs: 1, maxArgs: 4, parameterTypes: ['any', 'any', 'any', 'any'] },
  crypt: { minArgs: 1, maxArgs: 2, parameterTypes: ['str', 'str'] },
  ctime: { minArgs: 0, maxArgs: 1, parameterTypes: ['int'] },
  curl: { minArgs: 1, maxArgs: 3, parameterTypes: ['str', 'any', 'int'] },
  db_disk_size: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  decode_base64: { minArgs: 1, maxArgs: 2, parameterTypes: ['str', 'any'] },
  decode_binary: { minArgs: 1, maxArgs: 2, parameterTypes: ['str', 'any'] },
  delete_property: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'str'] },
  delete_verb: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'any'] },
  descendants: { minArgs: 1, maxArgs: 2, parameterTypes: ['any', 'any'] },
  disassemble: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'any'] },
  distance: { minArgs: 2, maxArgs: 2, parameterTypes: ['list', 'list'] },
  dump_database: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  encode_base64: { minArgs: 1, maxArgs: 2, parameterTypes: ['str', 'any'] },
  encode_binary: { minArgs: 0, maxArgs: -1, parameterTypes: [] },
  equal: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'any'] },
  eval: { minArgs: 1, maxArgs: -1, parameterTypes: ['str'] },
  exec: { minArgs: 1, maxArgs: 3, parameterTypes: ['list', 'str', 'list'] },
  exp: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  explode: { minArgs: 1, maxArgs: 3, parameterTypes: ['str', 'str', 'int'] },
  file_chmod: { minArgs: 2, maxArgs: 2, parameterTypes: ['str', 'str'] },
  file_close: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  file_count_lines: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  file_eof: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  file_flush: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  file_grep: { minArgs: 2, maxArgs: 3, parameterTypes: ['int', 'str', 'int'] },
  file_handles: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  file_last_access: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  file_last_change: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  file_last_modify: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  file_list: { minArgs: 1, maxArgs: 2, parameterTypes: ['str', 'any'] },
  file_mkdir: { minArgs: 1, maxArgs: 1, parameterTypes: ['str'] },
  file_mode: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  file_name: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  file_open: { minArgs: 2, maxArgs: 2, parameterTypes: ['str', 'str'] },
  file_openmode: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  file_read: { minArgs: 2, maxArgs: 2, parameterTypes: ['int', 'int'] },
  file_readline: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  file_readlines: { minArgs: 3, maxArgs: 3, parameterTypes: ['int', 'int', 'int'] },
  file_remove: { minArgs: 1, maxArgs: 1, parameterTypes: ['str'] },
  file_rename: { minArgs: 2, maxArgs: 2, parameterTypes: ['str', 'str'] },
  file_rmdir: { minArgs: 1, maxArgs: 1, parameterTypes: ['str'] },
  file_seek: { minArgs: 3, maxArgs: 3, parameterTypes: ['int', 'int', 'str'] },
  file_size: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  file_stat: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  file_tell: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  file_type: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  file_write: { minArgs: 2, maxArgs: 2, parameterTypes: ['int', 'str'] },
  file_writeline: { minArgs: 2, maxArgs: 2, parameterTypes: ['int', 'str'] },
  finished_tasks: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  floatstr: { minArgs: 2, maxArgs: 3, parameterTypes: ['float', 'int', 'any'] },
  floor: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  flush_input: { minArgs: 1, maxArgs: 2, parameterTypes: ['obj', 'any'] },
  force_input: { minArgs: 2, maxArgs: 3, parameterTypes: ['obj', 'str', 'any'] },
  forked: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  frandom: { minArgs: 1, maxArgs: 2, parameterTypes: ['float', 'float'] },
  ftime: { minArgs: 0, maxArgs: 1, parameterTypes: ['int'] },
  function_info: { minArgs: 0, maxArgs: 1, parameterTypes: ['str'] },
  gc_stats: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  generate_json: { minArgs: 1, maxArgs: 3, parameterTypes: ['any', 'str', 'any'] },
  getenv: { minArgs: 1, maxArgs: 1, parameterTypes: ['str'] },
  idle_seconds: { minArgs: 1, maxArgs: 1, parameterTypes: ['obj'] },
  index: { minArgs: 2, maxArgs: 4, parameterTypes: ['str', 'str', 'any', 'int'] },
  is_clear_property: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'str'] },
  is_member: { minArgs: 2, maxArgs: 3, parameterTypes: ['any', 'any', 'int'] },
  is_player: { minArgs: 1, maxArgs: 1, parameterTypes: ['obj'] },
  isa: { minArgs: 2, maxArgs: 3, parameterTypes: ['any', 'any', 'int'] },
  kill_task: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  length: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  listappend: { minArgs: 2, maxArgs: 3, parameterTypes: ['list', 'any', 'int'] },
  listdelete: { minArgs: 2, maxArgs: 2, parameterTypes: ['list', 'int'] },
  listen: { minArgs: 2, maxArgs: 3, parameterTypes: ['obj', 'any', 'map'] },
  listeners: { minArgs: 0, maxArgs: 1, parameterTypes: ['any'] },
  listinsert: { minArgs: 2, maxArgs: 3, parameterTypes: ['list', 'any', 'int'] },
  listset: { minArgs: 3, maxArgs: 3, parameterTypes: ['list', 'any', 'int'] },
  load_server_options: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  locate_by_name: { minArgs: 1, maxArgs: 2, parameterTypes: ['str', 'int'] },
  locations: { minArgs: 1, maxArgs: 3, parameterTypes: ['obj', 'obj', 'int'] },
  log: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  log10: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  log_cache_stats: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  malloc_stats: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  mapdelete: { minArgs: 2, maxArgs: 2, parameterTypes: ['map', 'any'] },
  maphaskey: { minArgs: 2, maxArgs: 3, parameterTypes: ['map', 'any', 'int'] },
  mapkeys: { minArgs: 1, maxArgs: 1, parameterTypes: ['map'] },
  mapvalues: { minArgs: 1, maxArgs: -1, parameterTypes: ['map'] },
  match: { minArgs: 2, maxArgs: 3, parameterTypes: ['str', 'str', 'any'] },
  max: { minArgs: 1, maxArgs: -1, parameterTypes: ['numeric'] },
  max_object: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  memory_usage: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  min: { minArgs: 1, maxArgs: -1, parameterTypes: ['numeric'] },
  move: { minArgs: 2, maxArgs: 3, parameterTypes: ['obj', 'obj', 'int'] },
  new_waif: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  next_recycled_object: { minArgs: 0, maxArgs: 1, parameterTypes: ['obj'] },
  notify: { minArgs: 2, maxArgs: 4, parameterTypes: ['obj', 'str', 'any', 'any'] },
  object_bytes: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  occupants: { minArgs: 1, maxArgs: 4, parameterTypes: ['list', 'any', 'int', 'int'] },
  open_network_connection: { minArgs: 2, maxArgs: 3, parameterTypes: ['str', 'int', 'map'] },
  output_delimiters: { minArgs: 1, maxArgs: 1, parameterTypes: ['obj'] },
  owned_objects: { minArgs: 1, maxArgs: 1, parameterTypes: ['obj'] },
  parent: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  parents: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  parse_ansi: { minArgs: 1, maxArgs: 1, parameterTypes: ['str'] },
  parse_json: { minArgs: 1, maxArgs: 2, parameterTypes: ['str', 'str'] },
  pass: { minArgs: 0, maxArgs: -1, parameterTypes: [] },
  pcre_cache_stats: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  pcre_match: { minArgs: 2, maxArgs: 4, parameterTypes: ['str', 'str', 'int', 'int'] },
  pcre_replace: { minArgs: 2, maxArgs: 2, parameterTypes: ['str', 'str'] },
  players: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  properties: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  property_info: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'str'] },
  queue_info: { minArgs: 0, maxArgs: 1, parameterTypes: ['obj'] },
  queued_tasks: { minArgs: 0, maxArgs: 2, parameterTypes: ['int', 'int'] },
  raise: { minArgs: 1, maxArgs: 3, parameterTypes: ['any', 'str', 'any'] },
  random: { minArgs: 0, maxArgs: 2, parameterTypes: ['int', 'int'] },
  random_bytes: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  read: { minArgs: 0, maxArgs: 2, parameterTypes: ['obj', 'any'] },
  read_http: { minArgs: 1, maxArgs: 2, parameterTypes: ['str', 'obj'] },
  read_stdin: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  recreate: { minArgs: 2, maxArgs: 3, parameterTypes: ['obj', 'obj', 'obj'] },
  recycle: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  recycled_objects: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  relative_heading: { minArgs: 2, maxArgs: 2, parameterTypes: ['list', 'list'] },
  remove_ansi: { minArgs: 1, maxArgs: 1, parameterTypes: ['str'] },
  renumber: { minArgs: 1, maxArgs: 1, parameterTypes: ['obj'] },
  reseed_random: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  reset_max_object: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  respond_to: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'str'] },
  resume: { minArgs: 1, maxArgs: 2, parameterTypes: ['int', 'any'] },
  reverse: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  rindex: { minArgs: 2, maxArgs: 4, parameterTypes: ['str', 'str', 'any', 'int'] },
  rmatch: { minArgs: 2, maxArgs: 3, parameterTypes: ['str', 'str', 'any'] },
  round: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  run_gc: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  salt: { minArgs: 2, maxArgs: 2, parameterTypes: ['str', 'str'] },
  seconds_left: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  server_log: { minArgs: 1, maxArgs: 2, parameterTypes: ['str', 'any'] },
  server_version: { minArgs: 0, maxArgs: 1, parameterTypes: ['any'] },
  set_connection_option: { minArgs: 3, maxArgs: 3, parameterTypes: ['obj', 'str', 'any'] },
  set_player_flag: { minArgs: 2, maxArgs: 2, parameterTypes: ['obj', 'any'] },
  set_property_info: { minArgs: 3, maxArgs: 3, parameterTypes: ['any', 'str', 'list'] },
  set_task_local: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  set_task_perms: { minArgs: 1, maxArgs: 1, parameterTypes: ['obj'] },
  set_thread_mode: { minArgs: 0, maxArgs: 1, parameterTypes: ['int'] },
  set_verb_args: { minArgs: 3, maxArgs: 3, parameterTypes: ['any', 'any', 'list'] },
  set_verb_code: { minArgs: 3, maxArgs: 3, parameterTypes: ['any', 'any', 'list'] },
  set_verb_info: { minArgs: 3, maxArgs: 3, parameterTypes: ['any', 'any', 'list'] },
  setadd: { minArgs: 2, maxArgs: 2, parameterTypes: ['list', 'any'] },
  setremove: { minArgs: 2, maxArgs: 2, parameterTypes: ['list', 'any'] },
  shutdown: { minArgs: 0, maxArgs: 2, parameterTypes: ['str', 'any'] },
  simplex_noise: { minArgs: 1, maxArgs: 1, parameterTypes: ['list'] },
  sin: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  sinh: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  slice: { minArgs: 1, maxArgs: 3, parameterTypes: ['list', 'any', 'any'] },
  sort: { minArgs: 1, maxArgs: 4, parameterTypes: ['list', 'list', 'int', 'int'] },
  spellcheck: { minArgs: 1, maxArgs: 1, parameterTypes: ['str'] },
  sqlite_close: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  sqlite_execute: { minArgs: 3, maxArgs: 3, parameterTypes: ['int', 'str', 'list'] },
  sqlite_handles: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  sqlite_info: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  sqlite_interrupt: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  sqlite_last_insert_row_id: { minArgs: 1, maxArgs: 1, parameterTypes: ['int'] },
  sqlite_limit: { minArgs: 3, maxArgs: 3, parameterTypes: ['int', 'any', 'int'] },
  sqlite_open: { minArgs: 1, maxArgs: 2, parameterTypes: ['str', 'int'] },
  sqlite_query: { minArgs: 2, maxArgs: 3, parameterTypes: ['int', 'str', 'any'] },
  sqrt: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  strcmp: { minArgs: 2, maxArgs: 2, parameterTypes: ['str', 'str'] },
  string_hash: { minArgs: 1, maxArgs: 3, parameterTypes: ['str', 'str', 'any'] },
  string_hmac: { minArgs: 2, maxArgs: 4, parameterTypes: ['str', 'str', 'str', 'any'] },
  strsub: { minArgs: 3, maxArgs: 4, parameterTypes: ['str', 'str', 'str', 'any'] },
  strtr: { minArgs: 3, maxArgs: 4, parameterTypes: ['str', 'str', 'str', 'any'] },
  substitute: { minArgs: 2, maxArgs: 2, parameterTypes: ['str', 'list'] },
  suspend: { minArgs: 0, maxArgs: 1, parameterTypes: ['numeric'] },
  switch_player: { minArgs: 2, maxArgs: 3, parameterTypes: ['obj', 'obj', 'int'] },
  tan: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  tanh: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  task_id: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  task_local: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  task_perms: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  task_stack: { minArgs: 1, maxArgs: 3, parameterTypes: ['int', 'any', 'any'] },
  thread_pool: { minArgs: 2, maxArgs: 3, parameterTypes: ['str', 'str', 'int'] },
  threads: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  ticks_left: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  time: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  tofloat: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  toint: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  toliteral: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  toobj: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  tostr: { minArgs: 0, maxArgs: -1, parameterTypes: [] },
  trunc: { minArgs: 1, maxArgs: 1, parameterTypes: ['float'] },
  typeof: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  unlisten: { minArgs: 1, maxArgs: 2, parameterTypes: ['any', 'any'] },
  url_decode: { minArgs: 1, maxArgs: 1, parameterTypes: ['str'] },
  url_encode: { minArgs: 1, maxArgs: 1, parameterTypes: ['str'] },
  usage: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  valid: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  value_bytes: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  value_hash: { minArgs: 1, maxArgs: 3, parameterTypes: ['any', 'str', 'any'] },
  value_hmac: { minArgs: 2, maxArgs: 4, parameterTypes: ['any', 'str', 'str', 'any'] },
  verb_args: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'any'] },
  verb_cache_stats: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  verb_code: { minArgs: 2, maxArgs: 4, parameterTypes: ['any', 'any', 'any', 'any'] },
  verb_info: { minArgs: 2, maxArgs: 2, parameterTypes: ['any', 'any'] },
  verbs: { minArgs: 1, maxArgs: 1, parameterTypes: ['any'] },
  waif_stats: { minArgs: 0, maxArgs: 0, parameterTypes: [] },
  yin: { minArgs: 0, maxArgs: 3, parameterTypes: ['numeric', 'int', 'int'] },
} as const satisfies Record<string, MooBuiltinMetadata>;

export type MooBuiltinName = keyof typeof MOO_BUILTIN_METADATA;

export const MOO_BUILTIN_NAMES = Object.keys(MOO_BUILTIN_METADATA).sort() as MooBuiltinName[];

export function getMooBuiltinMetadata(name: string): MooBuiltinMetadata | null {
  return MOO_BUILTIN_METADATA[name.toLowerCase() as MooBuiltinName] ?? null;
}

export function formatMooBuiltinArity(metadata: MooBuiltinMetadata): string {
  if (metadata.maxArgs < 0) {
    return `at least ${metadata.minArgs} ${metadata.minArgs === 1 ? 'argument' : 'arguments'}`;
  }

  if (metadata.minArgs === metadata.maxArgs) {
    return `${metadata.minArgs} ${metadata.minArgs === 1 ? 'argument' : 'arguments'}`;
  }

  return `${metadata.minArgs} to ${metadata.maxArgs} arguments`;
}
