export const MOO_LANGUAGE_ID = 'moocode';
export const PLAINTEXT_LANGUAGE_ID = 'plaintext';
export const MOO_CODE_ACTION_QUICKFIX_KIND = 'quickfix';
export const MOO_CODE_ACTION_FIX_ALL_KIND = 'source.fixAll.moocode';

export const MOO_SESSION_TYPES = ['moo-code', 'moocode', 'lambdamoo'] as const;

export const MOO_IDENTIFIER_PATTERN_SOURCE = '[A-Za-z_][A-Za-z0-9_]*';
export const MOO_SYSTEM_REFERENCE_PATTERN_SOURCE = `\\$${MOO_IDENTIFIER_PATTERN_SOURCE}`;

export const STATEMENT_KEYWORDS = [
  'if',
  'else',
  'elseif',
  'endif',
  'for',
  'in',
  'endfor',
  'fork',
  'endfork',
  'return',
  'while',
  'endwhile',
  'try',
  'except',
  'finally',
  'endtry',
  'ANY',
  'break',
  'continue',
] as const;

export const OPERATOR_WORDS = ['and', 'or', 'bitor', 'bitand', 'bitxor'] as const;

export const ERROR_CONSTANTS = [
  'E_NONE',
  'E_TYPE',
  'E_DIV',
  'E_PERM',
  'E_PROPNF',
  'E_VERBNF',
  'E_VARNF',
  'E_INVIND',
  'E_RECMOVE',
  'E_MAXREC',
  'E_RANGE',
  'E_ARGS',
  'E_NACC',
  'E_INVARG',
  'E_QUOTA',
  'E_FLOAT',
  'E_FILE',
  'E_EXEC',
  'E_INTRPT',
] as const;

export const BUILTIN_VARIABLES = [
  'player',
  'this',
  'caller',
  'verb',
  'args',
  'argstr',
  'dobj',
  'dobjstr',
  'prepstr',
  'iobj',
  'iobjstr',
] as const;

export const SYSTEM_REFERENCES = [
  '$login',
  '$local',
  '$network',
  '$player',
  '$room',
  '$string_utils',
  '$telnet_utils',
  '$utils',
  '$wiz',
] as const;

export const BUILTIN_FUNCTIONS = [
  'abs',
  'acos',
  'acosh',
  'add_property',
  'add_verb',
  'all_members',
  'ancestors',
  'anon',
  'argon2',
  'argon2_verify',
  'asin',
  'asinh',
  'atan',
  'atan2',
  'atanh',
  'background_test',
  'binary_hash',
  'binary_hmac',
  'boot_player',
  'buffered_output_length',
  'call_function',
  'caller_perms',
  'callers',
  'cbrt',
  'ceil',
  'children',
  'chparent',
  'chparents',
  'chr',
  'clear_property',
  'connected_players',
  'connected_seconds',
  'connection_info',
  'connection_name',
  'connection_name_lookup',
  'connection_options',
  'cos',
  'cosh',
  'create',
  'crypt',
  'ctime',
  'curl',
  'db_disk_size',
  'decode_base64',
  'decode_binary',
  'delete_property',
  'delete_verb',
  'descendants',
  'disassemble',
  'distance',
  'dump_database',
  'encode_base64',
  'encode_binary',
  'equal',
  'eval',
  'exec',
  'exp',
  'explode',
  'file_chmod',
  'file_close',
  'file_count_lines',
  'file_eof',
  'file_flush',
  'file_grep',
  'file_handles',
  'file_last_access',
  'file_last_change',
  'file_last_modify',
  'file_list',
  'file_mkdir',
  'file_mode',
  'file_name',
  'file_open',
  'file_openmode',
  'file_read',
  'file_readline',
  'file_readlines',
  'file_remove',
  'file_rename',
  'file_rmdir',
  'file_seek',
  'file_size',
  'file_stat',
  'file_tell',
  'file_type',
  'file_write',
  'file_writeline',
  'finished_tasks',
  'floatstr',
  'floor',
  'flush_input',
  'force_input',
  'forked',
  'frandom',
  'ftime',
  'function_info',
  'gc_stats',
  'generate_json',
  'getenv',
  'idle_seconds',
  'index',
  'is_clear_property',
  'is_member',
  'is_player',
  'isa',
  'kill_task',
  'length',
  'listappend',
  'listdelete',
  'listen',
  'listeners',
  'listinsert',
  'listset',
  'load_server_options',
  'locate_by_name',
  'locations',
  'log',
  'log10',
  'log_cache_stats',
  'malloc_stats',
  'mapdelete',
  'maphaskey',
  'mapkeys',
  'mapvalues',
  'match',
  'max',
  'max_object',
  'memory_usage',
  'min',
  'move',
  'new_waif',
  'next_recycled_object',
  'notify',
  'object_bytes',
  'occupants',
  'open_network_connection',
  'output_delimiters',
  'owned_objects',
  'parent',
  'parents',
  'parse_ansi',
  'parse_json',
  'pass',
  'pcre_cache_stats',
  'pcre_match',
  'pcre_replace',
  'players',
  'properties',
  'property_info',
  'queue_info',
  'queued_tasks',
  'raise',
  'random',
  'random_bytes',
  'read',
  'read_http',
  'read_stdin',
  'recreate',
  'recycle',
  'recycled_objects',
  'relative_heading',
  'remove_ansi',
  'renumber',
  'reseed_random',
  'reset_max_object',
  'respond_to',
  'resume',
  'reverse',
  'rindex',
  'rmatch',
  'round',
  'run_gc',
  'salt',
  'seconds_left',
  'server_log',
  'server_version',
  'set_connection_option',
  'set_player_flag',
  'set_property_info',
  'set_task_local',
  'set_task_perms',
  'set_thread_mode',
  'set_verb_args',
  'set_verb_code',
  'set_verb_info',
  'setadd',
  'setremove',
  'shutdown',
  'simplex_noise',
  'sin',
  'sinh',
  'slice',
  'sort',
  'spellcheck',
  'sqlite_close',
  'sqlite_execute',
  'sqlite_handles',
  'sqlite_info',
  'sqlite_interrupt',
  'sqlite_last_insert_row_id',
  'sqlite_limit',
  'sqlite_open',
  'sqlite_query',
  'sqrt',
  'strcmp',
  'string_hash',
  'string_hmac',
  'strsub',
  'strtr',
  'substitute',
  'suspend',
  'switch_player',
  'tan',
  'tanh',
  'task_id',
  'task_local',
  'task_perms',
  'task_stack',
  'thread_pool',
  'threads',
  'ticks_left',
  'time',
  'tofloat',
  'toint',
  'toliteral',
  'toobj',
  'tostr',
  'trunc',
  'typeof',
  'unlisten',
  'url_decode',
  'url_encode',
  'usage',
  'valid',
  'value_bytes',
  'value_hash',
  'value_hmac',
  'verb_args',
  'verb_cache_stats',
  'verb_code',
  'verb_info',
  'verbs',
  'waif_stats',
  'yin',
] as const;

export type MooBlockKind = 'if' | 'for' | 'while' | 'fork' | 'try';
export type MooMiddleKeyword = 'elseif' | 'else' | 'except' | 'finally';

export type MooBlockDefinition = {
  close: string;
  middle?: readonly string[];
  isLoop?: boolean;
};

export const MOO_BLOCKS: Record<MooBlockKind, MooBlockDefinition> = {
  if: { close: 'endif', middle: ['elseif', 'else'] },
  for: { close: 'endfor', isLoop: true },
  while: { close: 'endwhile', isLoop: true },
  fork: { close: 'endfork' },
  try: { close: 'endtry', middle: ['except', 'finally'] },
};

export const MOO_CLOSE_KEYWORDS = Object.fromEntries(
  Object.entries(MOO_BLOCKS).map(([kind, block]) => [block.close, kind]),
) as Record<string, MooBlockKind>;

export const MOO_MIDDLE_KEYWORDS = Object.fromEntries(
  Object.entries(MOO_BLOCKS).flatMap(([kind, block]) =>
    (block.middle ?? []).map((keyword) => [keyword, kind]),
  ),
) as Record<string, MooBlockKind>;

export const MOO_INDENT_OPEN_KEYWORDS = [
  ...Object.keys(MOO_BLOCKS),
  ...Object.values(MOO_BLOCKS).flatMap((block) => block.middle ?? []),
] as const;
